language: node_js
node_js: 14.15.4
services: docker

stages:
  - build
  - publish

branches:
  only:
  - master

jobs:
  include:
    # Check prettier linting and build typescript
    # Check the current version is different than the published
    - stage: build
      script:
        - make build
        - make check
    # Build and publish to npm
    - stage: publish
      if: branch == master AND (NOT (type IN (push, pull_request)))
      before_script:
        - npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
      script:
        # Build the npm repo
        - make build
        # Push to npm
        - make push
